server:
  port: ${PORT}
spring:
  security:
    user:
      name: madhurendra
      password: madhurendra
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.security: DEBUG

