server:
  port: ${PORT}
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

